version: '3'

services:
  dbapi_hasura:
    image: hasura/graphql-engine:latest
    container_name: dbapi_hasura
    ports:
      - 8081:8080
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DBU}:${DBP}@${DBN}:5432/db_leprovencal
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    networks:
      - localaccess
    depends_on:
      - db_leprovencal
  dbapi_leprovencal:
    image: postgrest/postgrest
    container_name: dbapi_postgrest
    ports:
      - 8082:3000
    networks:
      - localaccess
    depends_on:
      - db_leprovencal
    environment:
      PGRST_DB_URI: postgres://${DBU}:${DBP}@${DBN}:5432/db_leprovencal
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: ${DBU} #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
  db_leprovencal:
    image: pastaga/db_leprovencal:1
    container_name: db_leprovencal
    expose:
      - 5432
    networks:
      - localaccess
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DBN}
      - POSTGRES_USER=${DBU}
      - POSTGRES_PASSWORD=${DBP}
    
networks:
  localaccess:
    driver: bridge